# Replace the text below to customize your site
site_name: 33 DUDU
site_description: Master in Design for Emergent Futures
site_author: QIANYIN DU
copyright: Copyleft 2023 "QIANYIN DU" - GNU Free Documentation License
repo_name: 'Future Hacker progress'
site_url: https://33dudu.github.io/magicreator/
repo_url: 'https://github.com/33dudu/magicreator'


nav:
  - ENTRY: index.md 
  - About: about/me.md
  - Master project:
      - GenTe Art Movement: project/gente.md
  - Reflections :
      - Term 1:
          - Landing: term1/01-Landing.md
          - Design Studio 01: 
             - Design Studio: term1/03-Design Studio 01.md 
             - Intervention: term1/Intervention 01.md
          - Documenting Design: term1/04- Documenting Design.md
          - AoWS: term1/02-Atlas of Weak Signals.md
          - The Machine Paradox: term1/05- The Machine Paradox.md
          - Living with Your Own Ideas: term1/06- Living with Your Own Ideas.md
          - Biology Zero: 
              - Biology-Zero: term1/07- Biology-Zero.md
              - G.M.O: term1/10- G.M.O.md
          - Agriculture Zero: term1/08- Agriculture-Zero.md
          - Design With Others: term1/09- Design With Others.md
      




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/d.q_y/?hl=en/


theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: cyan
  font:
    # See available fonts at https://fonts.google.com/
    text: Ubuntu
    code: VT323 
  icon:
    logo: images/dudu.png
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox


markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format  
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - tables
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css


extra_javascript:
  - custom.js